title: My Site
description: Home of harrypujols.com
baseurl: "" # or "/subdir"
url: "https://yourdomain.com"
collections:
  posts:
    output: true
  pages:
    output: true
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  # Add jekyll-tagging or other plugins if needed