title: Desktop
description: Harry's Desktop
baseurl: "/desktop"
url: "https://harrypujols.com"
collections:
  posts:
    output: true
  pages:
    output: true
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  # Add jekyll-tagging or other plugins if needed
